name: click_here
description: A new Flutter project.


version: 1.2.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  google_mobile_ads: ^2.4.0
  google_fonts: ^4.0.3
  firebase_core: ^2.9.0
  cloud_firestore: ^4.5.1
  firebase_auth: ^4.4.0
  google_sign_in: ^6.1.0
  shared_preferences: ^2.1.0
  velocity_x: ^3.6.0
  font_awesome_flutter: ^10.4.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
   - assets/images/logo.png
   - assets/images/boton.png
   - assets/images/boton2.png
   - assets/images/botonX2A.png
   - assets/images/botonX2D.png
